//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.FabricanteAService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectQuoteRequest", Namespace="http://schemas.datacontract.org/2004/07/FabricanteA")]
    [System.SerializableAttribute()]
    public partial class ObjectQuoteRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOffice.FabricanteAService.Music[] ListaMusicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCallbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOffice.FabricanteAService.Music[] ListaMusicas {
            get {
                return this.ListaMusicasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMusicasField, value) != true)) {
                    this.ListaMusicasField = value;
                    this.RaisePropertyChanged("ListaMusicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCallback {
            get {
                return this.WSCallbackField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCallbackField, value) != true)) {
                    this.WSCallbackField = value;
                    this.RaisePropertyChanged("WSCallback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Music", Namespace="http://schemas.datacontract.org/2004/07/FabricanteA")]
    [System.SerializableAttribute()]
    public partial class Music : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectCDRequest", Namespace="http://schemas.datacontract.org/2004/07/FabricanteA")]
    [System.SerializableAttribute()]
    public partial class ObjectCDRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOffice.FabricanteAService.Music[] ListaMusicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCallbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOffice.FabricanteAService.Music[] ListaMusicas {
            get {
                return this.ListaMusicasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMusicasField, value) != true)) {
                    this.ListaMusicasField = value;
                    this.RaisePropertyChanged("ListaMusicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCallback {
            get {
                return this.WSCallbackField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCallbackField, value) != true)) {
                    this.WSCallbackField = value;
                    this.RaisePropertyChanged("WSCallback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FabricanteAService.IFabricanteAService")]
    public interface IFabricanteAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteAService/getQuote", ReplyAction="http://tempuri.org/IFabricanteAService/getQuoteResponse")]
        double getQuote(BackOffice.FabricanteAService.ObjectQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteAService/MakeCD", ReplyAction="http://tempuri.org/IFabricanteAService/MakeCDResponse")]
        string MakeCD(BackOffice.FabricanteAService.ObjectCDRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFabricanteAServiceChannel : BackOffice.FabricanteAService.IFabricanteAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FabricanteAServiceClient : System.ServiceModel.ClientBase<BackOffice.FabricanteAService.IFabricanteAService>, BackOffice.FabricanteAService.IFabricanteAService {
        
        public FabricanteAServiceClient() {
        }
        
        public FabricanteAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FabricanteAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricanteAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricanteAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getQuote(BackOffice.FabricanteAService.ObjectQuoteRequest request) {
            return base.Channel.getQuote(request);
        }
        
        public string MakeCD(BackOffice.FabricanteAService.ObjectCDRequest request) {
            return base.Channel.MakeCD(request);
        }
    }
}
