//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.TransportadoraServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportJobRequest", Namespace="http://schemas.datacontract.org/2004/07/Transportadora")]
    [System.SerializableAttribute()]
    public partial class TransportJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCallbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encomendaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fabricaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAdress {
            get {
                return this.DeliveryAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAdressField, value) != true)) {
                    this.DeliveryAdressField = value;
                    this.RaisePropertyChanged("DeliveryAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCallback {
            get {
                return this.WSCallbackField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCallbackField, value) != true)) {
                    this.WSCallbackField = value;
                    this.RaisePropertyChanged("WSCallback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string encomendaID {
            get {
                return this.encomendaIDField;
            }
            set {
                if ((object.ReferenceEquals(this.encomendaIDField, value) != true)) {
                    this.encomendaIDField = value;
                    this.RaisePropertyChanged("encomendaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fabrica {
            get {
                return this.fabricaField;
            }
            set {
                if ((object.ReferenceEquals(this.fabricaField, value) != true)) {
                    this.fabricaField = value;
                    this.RaisePropertyChanged("fabrica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportJobPriceResponse", Namespace="http://schemas.datacontract.org/2004/07/Transportadora")]
    [System.SerializableAttribute()]
    public partial class TransportJobPriceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encomendaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refRequestPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string encomendaID {
            get {
                return this.encomendaIDField;
            }
            set {
                if ((object.ReferenceEquals(this.encomendaIDField, value) != true)) {
                    this.encomendaIDField = value;
                    this.RaisePropertyChanged("encomendaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refRequestPrice {
            get {
                return this.refRequestPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.refRequestPriceField, value) != true)) {
                    this.refRequestPriceField = value;
                    this.RaisePropertyChanged("refRequestPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportJobPriceRequest", Namespace="http://schemas.datacontract.org/2004/07/Transportadora")]
    [System.SerializableAttribute()]
    public partial class TransportJobPriceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCallbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encomendaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fabricaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAdress {
            get {
                return this.DeliveryAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAdressField, value) != true)) {
                    this.DeliveryAdressField = value;
                    this.RaisePropertyChanged("DeliveryAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCallback {
            get {
                return this.WSCallbackField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCallbackField, value) != true)) {
                    this.WSCallbackField = value;
                    this.RaisePropertyChanged("WSCallback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string encomendaID {
            get {
                return this.encomendaIDField;
            }
            set {
                if ((object.ReferenceEquals(this.encomendaIDField, value) != true)) {
                    this.encomendaIDField = value;
                    this.RaisePropertyChanged("encomendaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fabrica {
            get {
                return this.fabricaField;
            }
            set {
                if ((object.ReferenceEquals(this.fabricaField, value) != true)) {
                    this.fabricaField = value;
                    this.RaisePropertyChanged("fabrica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransportadoraServiceReference.ITransportadoraService")]
    public interface ITransportadoraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportadoraService/TransportJob", ReplyAction="http://tempuri.org/ITransportadoraService/TransportJobResponse")]
        BackOffice.TransportadoraServiceReference.TransportJobPriceResponse TransportJob(BackOffice.TransportadoraServiceReference.TransportJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportadoraService/TransportJobPrice", ReplyAction="http://tempuri.org/ITransportadoraService/TransportJobPriceResponse")]
        BackOffice.TransportadoraServiceReference.TransportJobPriceRequest TransportJobPrice(BackOffice.TransportadoraServiceReference.TransportJobPriceRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransportadoraServiceChannel : BackOffice.TransportadoraServiceReference.ITransportadoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportadoraServiceClient : System.ServiceModel.ClientBase<BackOffice.TransportadoraServiceReference.ITransportadoraService>, BackOffice.TransportadoraServiceReference.ITransportadoraService {
        
        public TransportadoraServiceClient() {
        }
        
        public TransportadoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportadoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportadoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportadoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOffice.TransportadoraServiceReference.TransportJobPriceResponse TransportJob(BackOffice.TransportadoraServiceReference.TransportJobRequest request) {
            return base.Channel.TransportJob(request);
        }
        
        public BackOffice.TransportadoraServiceReference.TransportJobPriceRequest TransportJobPrice(BackOffice.TransportadoraServiceReference.TransportJobPriceRequest request) {
            return base.Channel.TransportJobPrice(request);
        }
    }
}
